### ISSUE TITLE
Error: Cannot find module './copyFiles'

### ISSUE THREAD

**Issue by strmer15** [webdriverio-community/wdio-html-reporter#61]
In https://github.com/rpii/wdio-html-reporter/commit/5a4aa6b81eac6c98a68ba99d5ea0429b6077d6a8, a new `import` was added to the `copyFiles` module - however, it's giving an error in our build system, since the file name is actually `copyfiles.ts` and not `copyFiles.ts`. My guess is that our docker instances have a case-sensitive file system and can't locate the file name correclty.

Please update https://github.com/rpii/wdio-html-reporter/blob/master/src/reportAggregator.ts#L9 to say `import copyFiles from "./copyFiles";` or rename `copyfiles.ts` to `copyFiles.ts`.

**Comment by rpii** [comment]
ooops my bad.  hadnt tested on linux yet.  Its fixed now

**Comment by strmer15** [comment]
Thanks for the quick fix @rpii !

**Comment by rpii** [comment]
no problem.  was trying to get it out there too fast

**Comment by strmer15** [comment]
@rpii Sorry to bother you again, but it seems like it's still incorrect - the `7.7.10` package that I just grabbed still has the wrong file case in it. I blew my `node_modules` away and reinstalled just to be sure, but it's still there. I verified that the `package.json` has the new version and the `README` has the new update, but the file name is still incorrect in the published package.

**Comment by strmer15** [comment]
Also, your repository URL in `package.json` says `"url": "git+ssh://git@github.com/%40rpii/wdio-html-reporter.git"`, looks like you need to remove the `%40` in it.

**Comment by rpii** [comment]
Chris,  when I rebuilt it it kept the lower case name since it was on
windows.  I had to clean everything and rebuild the lib folder to get it
correct
v11 should be good.

**Comment by strmer15** [comment]
Yay, looks good now 🎉 Thanks again, Rich!
